/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import enums.UseCase;
import java.awt.MouseInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDateTime;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import javafx.util.converter.LocalDateTimeStringConverter;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import enums.UseCase;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import session.Session;
import controler.Controler;
import domain.Message;
import domain.User;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.ListSelectionModel;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import model.TableModelFriends;

/**
 *
 * @author proxc
 */
public class FormMain extends javax.swing.JFrame {

    /**
     * Creates new form Home41
     */
    public FormMain() {
        initComponents();
        adjust();
        setListeners();
        updateUseCase();
        setTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFriends = new javax.swing.JTable();
        txtStatus = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAdd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pnlExit = new javax.swing.JPanel();
        lblExit = new javax.swing.JLabel();
        btnProfile = new javax.swing.JButton();
        btnSendFile = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPane = new javax.swing.JTextPane();
        btnSend = new javax.swing.JButton();
        txtMessage = new javax.swing.JTextField();
        lblFriend = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 47, 65));
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(850, 550));

        jPanel1.setBackground(new java.awt.Color(87, 190, 175));

        lblName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(255, 255, 255));
        lblName.setText("User");

        tblFriends.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFriends);

        txtStatus.setBackground(new java.awt.Color(87, 190, 175));
        txtStatus.setForeground(new java.awt.Color(255, 255, 255));
        txtStatus.setText("I am using npchat!");
        txtStatus.setBorder(null);
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/l1s.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(87, 190, 175));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add a friend by username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtStatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));

        pnlExit.setBackground(new java.awt.Color(132, 18, 18));

        lblExit.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setText("  X");

        javax.swing.GroupLayout pnlExitLayout = new javax.swing.GroupLayout(pnlExit);
        pnlExit.setLayout(pnlExitLayout);
        pnlExitLayout.setHorizontalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );
        pnlExitLayout.setVerticalGroup(
            pnlExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProfile.setText("View profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnSendFile.setText("Send file");
        btnSendFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendFileActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSendFile, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnProfile)
                        .addComponent(btnSendFile)
                        .addComponent(btnRemove))
                    .addComponent(pnlExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(txtPane);

        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMessageActionPerformed(evt);
            }
        });

        lblFriend.setForeground(new java.awt.Color(255, 255, 255));
        lblFriend.setText("Please select a friend!");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Last message recieved at:");

        lblTime.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 255, 255));
        lblTime.setText("n/a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(txtMessage)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFriend, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(277, 277, 277)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblTime)))
                        .addContainerGap(12, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFriend)
                    .addComponent(jLabel2)
                    .addComponent(lblTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void txtMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMessageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMessageActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if (txtAdd.getText() != null && txtAdd.getText().length() >= 3) {
            try {
                Controler.getInstance().sendAddFriend(txtAdd.getText());
                txtAdd.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                txtAdd.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Username must be at least 3 characters long!");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        FormProfile formProfile = new FormProfile(this, true, Session.getInstance().getSelectedFriend());
        formProfile.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        if (txtMessage.getText() != null && txtMessage.getText() != "" && txtMessage.getText() != " ") {
            try {
                SimpleAttributeSet attributes = new SimpleAttributeSet();
                attributes = new SimpleAttributeSet();
                Color bcg = new Color(36, 47, 65);

                attributes.addAttribute(StyleConstants.CharacterConstants.Bold, Boolean.TRUE);
                attributes.addAttribute(StyleConstants.CharacterConstants.Italic, Boolean.FALSE);
                attributes.addAttribute(StyleConstants.CharacterConstants.Foreground, bcg);

                txtPane.getDocument().insertString(txtPane.getDocument().getLength(), "\n" + Session.getInstance().getCurrentUser().getUsername() + ": " + txtMessage.getText(), attributes);
                Controler.getInstance().sendMessage(txtMessage.getText(), Session.getInstance().getSelectedFriend());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
            txtMessage.setText("");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        try {
            Controler.getInstance().sendRemove();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnSendFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendFileActionPerformed

        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        String s = null;
        try {
            File f = chooser.getSelectedFile();
            s = f.getAbsolutePath();
            if(!s.endsWith("jpg")){
                JOptionPane.showMessageDialog(FormMain.this, "Please choose a different picture!");
                return;
            }
            System.out.println(s);

            Controler.getInstance().sendFile(s);
            Controler.getInstance().sendFileData();
        } catch (Exception e) {

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendFileActionPerformed
    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFriend;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel pnlExit;
    private javax.swing.JTable tblFriends;
    private javax.swing.JTextField txtAdd;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextPane txtPane;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables

    private void adjust() {
        txtMessage.requestFocus();
        btnSendFile.setEnabled(false);
        btnRemove.setEnabled(false);
        btnSend.setEnabled(false);
        btnProfile.setEnabled(false);
        this.setLocationRelativeTo(null);
        lblName.setText(Session.getInstance().getCurrentUser().getUsername());
        if (Session.getInstance().getCurrentUser().getStatus() != null) {
            txtStatus.setText(Session.getInstance().getCurrentUser().getStatus());
        }
        Color bcg = new Color(36, 47, 65);

        this.getContentPane().setBackground(bcg);
        TableModelFriends tmf = new TableModelFriends(new ArrayList<User>());
        tblFriends.setModel(tmf);
        tblFriends.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    private void setListeners() {
        txtStatus.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                String oldStatus = Session.getInstance().getCurrentUser().getStatus();
                Session.getInstance().getCurrentUser().setStatus(txtStatus.getText());
                try {
                    Controler.getInstance().sendUpdateStatus();
                } catch (Exception e) {
                    txtStatus.setText(oldStatus);
                    Session.getInstance().getCurrentUser().setStatus(oldStatus);
                    JOptionPane.showMessageDialog(FormMain.this, e.getMessage());
                }
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
            }

            @Override
            public void changedUpdate(DocumentEvent de) {
            }
        });

        pnlExit.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                try {
                    JOptionPane.showMessageDialog(FormMain.this, "You have logged out successfuly!");
                    Controler.getInstance().sendLogout();
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
                System.exit(0);
            }
        });
        lblExit.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                try {
                    JOptionPane.showMessageDialog(FormMain.this, "You have logged out successfuly!");
                    Controler.getInstance().sendLogout();
                } catch (Exception e2) {
                    e2.printStackTrace();
                }
                System.exit(0);
            }
        });
        tblFriends.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSend.setEnabled(true);
                btnProfile.setEnabled(true);
                btnSendFile.setEnabled(true);

                int row = tblFriends.rowAtPoint(evt.getPoint());
                if (row >= 0) {
                    TableModelFriends tmp1 = (TableModelFriends) tblFriends.getModel();
                    Session.getInstance().setSelectedFriend(tmp1.getFriends().get(row));
                    btnRemove.setEnabled(true);
                    lblFriend.setText(Session.getInstance().getSelectedFriend().getUsername());
                    try {
                        Controler.sendGetMessages();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(FormMain.this, e.getMessage());
                    }
                }
            }
        });
    }

    private void updateUseCase() {
        try {
            Controler.getInstance()
                    .sendGetFriends();
        } catch (Exception e) {

        }
        switch (session.Session.getInstance().getCurrentUseCase()) {
            case LOGIN:

                break;
            case REGISTER:

                break;
            default:
            // code block
        }
    }

    public void showMessage(Exception e) {
        JOptionPane.showMessageDialog(FormMain.this, e.getMessage());
    }

    public void updateFriends(ArrayList<User> friendsList) {
        TableModelFriends tmf = new TableModelFriends(friendsList);
        tblFriends.setModel(tmf);
        tblFriends.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public void recieveMessage(Message m) {
        if (session.Session.getInstance().getSelectedFriend() != null) {
            if (Session.getInstance().getSelectedFriend().getUsername().equals(m.getSender().getUsername())) {
                lblTime.setText(m.getTimestamp().toString());
                SimpleAttributeSet attributes = new SimpleAttributeSet();
                attributes = new SimpleAttributeSet();
                Color bcg = new Color(87, 190, 175);
                attributes.addAttribute(StyleConstants.CharacterConstants.Bold, Boolean.TRUE);
                attributes.addAttribute(StyleConstants.CharacterConstants.Foreground, bcg);
                try {
                    txtPane.getDocument().insertString(txtPane.getDocument().getLength(), "\n" + m.getSender().getUsername() + ": " + m.getMessage(), attributes);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }

            }
        }
    }

    public void setMessages(ArrayList<Message> messages) {
        //txtPane.getDocument().insertString(txtPane.getDocument().getLength(), "\n" + Session.getInstance().getCurrentUser().getUsername() + ": " + txtMessage.getText(), attributes);
        txtPane.setText("");
        messages.sort((e1, e2) -> e1.getTimestamp().compareTo(e2.getTimestamp()));
        for (Message m : messages) {
            if (m.getSender().getUserId() == Session.getInstance().getCurrentUser().getUserId()) {
                try {
                    SimpleAttributeSet attributes = new SimpleAttributeSet();
                    attributes = new SimpleAttributeSet();
                    Color bcg = new Color(36, 47, 65);
                    attributes.addAttribute(StyleConstants.CharacterConstants.Bold, Boolean.TRUE);
                    attributes.addAttribute(StyleConstants.CharacterConstants.Foreground, bcg);
                    txtPane.getDocument().insertString(txtPane.getDocument().getLength(), "\n" + Session.getInstance().getCurrentUser().getUsername() + ": " + m.getMessage(), attributes);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Something went wrong! Please try again in a bit!");
                }
            } else {

                try {
                    SimpleAttributeSet attributes = new SimpleAttributeSet();
                    attributes = new SimpleAttributeSet();
                    Color bcg = new Color(87, 190, 175);
                    attributes.addAttribute(StyleConstants.CharacterConstants.Bold, Boolean.TRUE);
                    attributes.addAttribute(StyleConstants.CharacterConstants.Foreground, bcg);
                    txtPane.getDocument().insertString(txtPane.getDocument().getLength(), "\n" + m.getSender().getUsername() + ": " + m.getMessage(), attributes);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Something went wrong! Please try again in a bit!");
                }
            }
        }
        try {
            lblTime.setText(messages.get(messages.size() - 1).getTimestamp().toString());
        } catch (Exception e) {
            lblTime.setText("Not known");
        }

    }

    private void setTheme() {
        Color bcg = new Color(36, 47, 65);
        Color bcg1 = new Color(220, 220, 220);
        btnAdd.setBackground(bcg1);
        btnAdd.setForeground(bcg);
        btnAdd.setFocusPainted(false);
        btnAdd.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnSend.setBackground(bcg1);
        btnSend.setForeground(bcg);
        btnSend.setFocusPainted(false);
        btnSend.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnProfile.setBackground(bcg1);
        btnProfile.setForeground(bcg);
        btnProfile.setFocusPainted(false);
        btnProfile.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnSendFile.setBackground(bcg1);
        btnSendFile.setForeground(bcg);
        btnSendFile.setFocusPainted(false);
        btnSendFile.setFont(new Font("Tahoma", Font.BOLD, 12));
        btnRemove.setBackground(bcg1);
        btnRemove.setForeground(bcg);
        btnRemove.setFocusPainted(false);
        btnRemove.setFont(new Font("Tahoma", Font.BOLD, 12));
    }

}
